# Generated by Django 4.1.2 on 2022-12-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
