# Generated by Django 4.1.2 on 2022-12-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0002_alter_berita_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
