# Generated by Django 4.1.2 on 2022-12-11 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0003_berita_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berita',
            name='content',
        ),
    ]
